"use client";

import { useEffect, useMemo, useState } from "react";
import hljs from "highlight.js/lib/core";
import python from "highlight.js/lib/languages/python";
import cpp from "highlight.js/lib/languages/cpp";
import java from "highlight.js/lib/languages/java";
import javascript from "highlight.js/lib/languages/javascript";
import typescript from "highlight.js/lib/languages/typescript";
import go from "highlight.js/lib/languages/go";
import rust from "highlight.js/lib/languages/rust";
import csharp from "highlight.js/lib/languages/csharp";
import kotlin from "highlight.js/lib/languages/kotlin";
import { Copy, Check } from "lucide-react";

// Registering only the languages we offer keeps this at a fraction of the
// full highlight.js bundle.
const REGISTERED: Record<string, Parameters<typeof hljs.registerLanguage>[1]> = {
  python,
  cpp,
  java,
  javascript,
  typescript,
  go,
  rust,
  csharp,
  kotlin,
};

let initialised = false;
function ensureRegistered() {
  if (initialised) return;
  for (const [name, def] of Object.entries(REGISTERED)) hljs.registerLanguage(name, def);
  // Common aliases from fenced markdown blocks.
  hljs.registerAliases(["py"], { languageName: "python" });
  hljs.registerAliases(["c++", "cc"], { languageName: "cpp" });
  hljs.registerAliases(["js"], { languageName: "javascript" });
  hljs.registerAliases(["ts"], { languageName: "typescript" });
  hljs.registerAliases(["cs"], { languageName: "csharp" });
  hljs.registerAliases(["kt"], { languageName: "kotlin" });
  initialised = true;
}

export function CodeBlock({ code, language }: { code: string; language: string }) {
  const [copied, setCopied] = useState(false);

  const html = useMemo(() => {
    ensureRegistered();
    const lang = language.toLowerCase();
    try {
      if (hljs.getLanguage(lang)) return hljs.highlight(code, { language: lang }).value;
      return hljs.highlightAuto(code).value;
    } catch {
      // Fall back to plain text rather than losing the user's solution.
      return escapeHtml(code);
    }
  }, [code, language]);

  useEffect(() => {
    if (!copied) return;
    const t = setTimeout(() => setCopied(false), 1800);
    return () => clearTimeout(t);
  }, [copied]);

  return (
    <div className="group relative">
      <button
        onClick={async () => {
          try {
            await navigator.clipboard.writeText(code);
            setCopied(true);
          } catch {
            /* clipboard blocked — nothing useful to do */
          }
        }}
        className="absolute top-2 right-2 rounded-md border border-[var(--border)] bg-[var(--surface)] p-1.5 text-[var(--fg-subtle)] opacity-0 transition-all hover:text-[var(--fg)] group-hover:opacity-100 focus-visible:opacity-100"
        aria-label="Copy code"
      >
        {copied ? <Check className="size-3.5 text-[var(--easy)]" /> : <Copy className="size-3.5" />}
      </button>
      <pre className="overflow-x-auto rounded-lg border border-[var(--border)] bg-[var(--surface-2)] p-3.5 text-[0.8125rem] leading-relaxed">
        <code
          className="hljs font-mono"
          // Highlighted output is generated by highlight.js from the user's own
          // text; it escapes everything it doesn't emit itself.
          dangerouslySetInnerHTML={{ __html: html }}
        />
      </pre>
    </div>
  );
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
